services:
  open-webui:
    image: backplane/open-webui:0.6.15
    container_name: open-webui-finmars
    ports:
      - "8881:8080"
    networks:
      - arch-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=${TZ:-Europe/Luxembourg}
      - PIPELINES_API_KEY=${PIPELINES_API_KEY}
      - ENABLE_FOLLOW_UP_GENERATION=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_NAME=Finmars AI Assistant
    volumes:
      - open-webui:/app/backend/data
    restart: always

  agent-pipelines:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-pipelines
    ports:
      - "9299:9099"
    networks:
      - arch-network
    depends_on:
      - open-webui
    environment:
      - TZ=${TZ:-Europe/Luxembourg}
      - PIPELINES_API_KEY=${PIPELINES_API_KEY:-test}
      - PIPELINE_NAME=${PIPELINE_NAME:-Finmars AI Assistant Docker}
      - PROMPT_SOURCE=${PROMPT_SOURCE:-code}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FINMARS_EXPERT_TOKEN=${FINMARS_EXPERT_TOKEN}
      - FINMARS_BASE_URL=${FINMARS_BASE_URL}
      - FINMARS_REALM=${FINMARS_REALM}
      - FINMARS_SPACE=${FINMARS_SPACE}
      - ACTIVATE_PUBLIC_NAME=${ACTIVATE_PUBLIC_NAME:-false}
    restart: always

volumes:
  open-webui:
    driver: local

networks:
  arch-network:
    driver: bridge