from typing import Optional
from pydantic import BaseModel, Field

from .base import TransactionUniqueCodeOptionsEnum


class TransactionClass(BaseModel):
    id: int = Field(..., title="ID", ge=0, le=32767)
    user_code: str = Field(..., title="User code", max_length=255, min_length=1)
    name: str = Field("", title="Name", max_length=255)
    description: str = Field("", title="Description")


class TransactionTypeView(BaseModel):
    id: int = Field(..., title="ID", description="readonly")
    group: Optional[str] = Field(None, title="Group")
    user_code: Optional[str] = Field(None, title="User code", max_length=255)
    name: str = Field(..., title="Name", description="Human Readable Name of the object", max_length=255, min_length=1)
    short_name: Optional[str] = Field(None, title="Short name", description="Short Name of the object. Used in dropdown menus")
    public_name: Optional[str] = Field(None, title="Public name", description="Used if user does not have permissions to view object", max_length=255)
    notes: Optional[str] = Field(None, title="Notes", description="Notes, any useful information about the object")
    is_valid_for_all_portfolios: bool = Field(True, title="Is valid for all portfolios")
    is_valid_for_all_instruments: bool = Field(True, title="Is valid for all instruments")
    is_deleted: bool = Field(False, title="Is deleted", description="Mark object as deleted. Does not actually delete the object.")
    transaction_unique_code_expr: str = Field("", title="Transaction unique code expr", max_length=4096)
    transaction_unique_code_options: Optional[TransactionUniqueCodeOptionsEnum] = Field(None, title="Transaction unique code options")
    user_text_1: str = Field("", title="User text 1", max_length=4096)
    user_text_2: str = Field("", title="User text 2", max_length=4096)
    user_text_3: str = Field("", title="User text 3", max_length=4096)
    user_text_4: str = Field("", title="User text 4", max_length=4096)
    user_text_5: str = Field("", title="User text 5", max_length=4096)
    user_text_6: str = Field("", title="User text 6", max_length=4096)
    user_text_7: str = Field("", title="User text 7", max_length=4096)
    user_text_8: str = Field("", title="User text 8", max_length=4096)
    user_text_9: str = Field("", title="User text 9", max_length=4096)
    user_text_10: str = Field("", title="User text 10", max_length=4096)
    user_text_11: str = Field("", title="User text 11", max_length=4096)
    user_text_12: str = Field("", title="User text 12", max_length=4096)
    user_text_13: str = Field("", title="User text 13", max_length=4096)
    user_text_14: str = Field("", title="User text 14", max_length=4096)
    user_text_15: str = Field("", title="User text 15", max_length=4096)
    user_text_16: str = Field("", title="User text 16", max_length=4096)
    user_text_17: str = Field("", title="User text 17", max_length=4096)
    user_text_18: str = Field("", title="User text 18", max_length=4096)
    user_text_19: str = Field("", title="User text 19", max_length=4096)
    user_text_20: str = Field("", title="User text 20", max_length=4096)
    user_text_21: str = Field("", title="User text 21", max_length=4096)
    user_text_22: str = Field("", title="User text 22", max_length=4096)
    user_text_23: str = Field("", title="User text 23", max_length=4096)
    user_text_24: str = Field("", title="User text 24", max_length=4096)
    user_text_25: str = Field("", title="User text 25", max_length=4096)
    user_text_26: str = Field("", title="User text 26", max_length=4096)
    user_text_27: str = Field("", title="User text 27", max_length=4096)
    user_text_28: str = Field("", title="User text 28", max_length=4096)
    user_text_29: str = Field("", title="User text 29", max_length=4096)
    user_text_30: str = Field("", title="User text 30", max_length=4096)
    user_number_1: str = Field("", title="User number 1", max_length=4096)
    user_number_2: str = Field("", title="User number 2", max_length=4096)
    user_number_3: str = Field("", title="User number 3", max_length=4096)
    user_number_4: str = Field("", title="User number 4", max_length=4096)
    user_number_5: str = Field("", title="User number 5", max_length=4096)
    user_number_6: str = Field("", title="User number 6", max_length=4096)
    user_number_7: str = Field("", title="User number 7", max_length=4096)
    user_number_8: str = Field("", title="User number 8", max_length=4096)
    user_number_9: str = Field("", title="User number 9", max_length=4096)
    user_number_10: str = Field("", title="User number 10", max_length=4096)
    user_number_11: str = Field("", title="User number 11", max_length=4096)
    user_number_12: str = Field("", title="User number 12", max_length=4096)
    user_number_13: str = Field("", title="User number 13", max_length=4096)
    user_number_14: str = Field("", title="User number 14", max_length=4096)
    user_number_15: str = Field("", title="User number 15", max_length=4096)
    user_number_16: str = Field("", title="User number 16", max_length=4096)
    user_number_17: str = Field("", title="User number 17", max_length=4096)
    user_number_18: str = Field("", title="User number 18", max_length=4096)
    user_number_19: str = Field("", title="User number 19", max_length=4096)
    user_number_20: str = Field("", title="User number 20", max_length=4096)
    user_date_1: str = Field("", title="User date 1", max_length=4096)
    user_date_2: str = Field("", title="User date 2", max_length=4096)
    user_date_3: str = Field("", title="User date 3", max_length=4096)
    user_date_4: str = Field("", title="User date 4", max_length=4096)
    user_date_5: str = Field("", title="User date 5", max_length=4096)
    deleted_user_code: Optional[str] = Field(None, title="Deleted user code", description="readonly", max_length=255)