from typing import Optional
from pydantic import BaseModel, Field

from .base import TransactionUniqueCodeOptionsEnum


class TransactionClass(BaseModel):
    id: int = Field(..., title="ID", ge=0, le=32767)
    user_code: str = Field(..., title="User code", max_length=255, min_length=1)
    name: Optional[str] = Field(None, title="Name", max_length=255)
    description: Optional[str] = Field(None, title="Description")


class TransactionTypeView(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="readonly")
    group: Optional[str] = Field(None, title="Group")
    user_code: Optional[str] = Field(None, title="User code", max_length=255)
    name: str = Field(..., title="Name", description="Human Readable Name of the object", max_length=255, min_length=1)
    short_name: Optional[str] = Field(None, title="Short name", description="Short Name of the object. Used in dropdown menus")
    public_name: Optional[str] = Field(None, title="Public name", description="Used if user does not have permissions to view object", max_length=255)
    notes: Optional[str] = Field(None, title="Notes", description="Notes, any useful information about the object")
    is_valid_for_all_portfolios: Optional[bool] = Field(None, title="Is valid for all portfolios")
    is_valid_for_all_instruments: Optional[bool] = Field(None, title="Is valid for all instruments")
    is_deleted: Optional[bool] = Field(None, title="Is deleted", description="Mark object as deleted. Does not actually delete the object.")
    transaction_unique_code_expr: Optional[str] = Field(None, title="Transaction unique code expr", max_length=4096)
    transaction_unique_code_options: Optional[TransactionUniqueCodeOptionsEnum] = Field(None, title="Transaction unique code options")
    user_text_1: Optional[str] = Field(None, title="User text 1", max_length=4096)
    user_text_2: Optional[str] = Field(None, title="User text 2", max_length=4096)
    user_text_3: Optional[str] = Field(None, title="User text 3", max_length=4096)
    user_text_4: Optional[str] = Field(None, title="User text 4", max_length=4096)
    user_text_5: Optional[str] = Field(None, title="User text 5", max_length=4096)
    user_text_6: Optional[str] = Field(None, title="User text 6", max_length=4096)
    user_text_7: Optional[str] = Field(None, title="User text 7", max_length=4096)
    user_text_8: Optional[str] = Field(None, title="User text 8", max_length=4096)
    user_text_9: Optional[str] = Field(None, title="User text 9", max_length=4096)
    user_text_10: Optional[str] = Field(None, title="User text 10", max_length=4096)
    user_text_11: Optional[str] = Field(None, title="User text 11", max_length=4096)
    user_text_12: Optional[str] = Field(None, title="User text 12", max_length=4096)
    user_text_13: Optional[str] = Field(None, title="User text 13", max_length=4096)
    user_text_14: Optional[str] = Field(None, title="User text 14", max_length=4096)
    user_text_15: Optional[str] = Field(None, title="User text 15", max_length=4096)
    user_text_16: Optional[str] = Field(None, title="User text 16", max_length=4096)
    user_text_17: Optional[str] = Field(None, title="User text 17", max_length=4096)
    user_text_18: Optional[str] = Field(None, title="User text 18", max_length=4096)
    user_text_19: Optional[str] = Field(None, title="User text 19", max_length=4096)
    user_text_20: Optional[str] = Field(None, title="User text 20", max_length=4096)
    user_text_21: Optional[str] = Field(None, title="User text 21", max_length=4096)
    user_text_22: Optional[str] = Field(None, title="User text 22", max_length=4096)
    user_text_23: Optional[str] = Field(None, title="User text 23", max_length=4096)
    user_text_24: Optional[str] = Field(None, title="User text 24", max_length=4096)
    user_text_25: Optional[str] = Field(None, title="User text 25", max_length=4096)
    user_text_26: Optional[str] = Field(None, title="User text 26", max_length=4096)
    user_text_27: Optional[str] = Field(None, title="User text 27", max_length=4096)
    user_text_28: Optional[str] = Field(None, title="User text 28", max_length=4096)
    user_text_29: Optional[str] = Field(None, title="User text 29", max_length=4096)
    user_text_30: Optional[str] = Field(None, title="User text 30", max_length=4096)
    user_number_1: Optional[str] = Field(None, title="User number 1", max_length=4096)
    user_number_2: Optional[str] = Field(None, title="User number 2", max_length=4096)
    user_number_3: Optional[str] = Field(None, title="User number 3", max_length=4096)
    user_number_4: Optional[str] = Field(None, title="User number 4", max_length=4096)
    user_number_5: Optional[str] = Field(None, title="User number 5", max_length=4096)
    user_number_6: Optional[str] = Field(None, title="User number 6", max_length=4096)
    user_number_7: Optional[str] = Field(None, title="User number 7", max_length=4096)
    user_number_8: Optional[str] = Field(None, title="User number 8", max_length=4096)
    user_number_9: Optional[str] = Field(None, title="User number 9", max_length=4096)
    user_number_10: Optional[str] = Field(None, title="User number 10", max_length=4096)
    user_number_11: Optional[str] = Field(None, title="User number 11", max_length=4096)
    user_number_12: Optional[str] = Field(None, title="User number 12", max_length=4096)
    user_number_13: Optional[str] = Field(None, title="User number 13", max_length=4096)
    user_number_14: Optional[str] = Field(None, title="User number 14", max_length=4096)
    user_number_15: Optional[str] = Field(None, title="User number 15", max_length=4096)
    user_number_16: Optional[str] = Field(None, title="User number 16", max_length=4096)
    user_number_17: Optional[str] = Field(None, title="User number 17", max_length=4096)
    user_number_18: Optional[str] = Field(None, title="User number 18", max_length=4096)
    user_number_19: Optional[str] = Field(None, title="User number 19", max_length=4096)
    user_number_20: Optional[str] = Field(None, title="User number 20", max_length=4096)
    user_date_1: Optional[str] = Field(None, title="User date 1", max_length=4096)
    user_date_2: Optional[str] = Field(None, title="User date 2", max_length=4096)
    user_date_3: Optional[str] = Field(None, title="User date 3", max_length=4096)
    user_date_4: Optional[str] = Field(None, title="User date 4", max_length=4096)
    user_date_5: Optional[str] = Field(None, title="User date 5", max_length=4096)
    deleted_user_code: Optional[str] = Field(None, title="Deleted user code", description="readonly", max_length=255)